### ISSUE TITLE
hashgrid missing in repository

### ISSUE THREAD

**Issue by maltoe** [prspktve/prspktve.github.com#1]
Trying to compile the site, the sass converter gets called and spits out the following error:

``` sh
$ jekyll
[...]
Calling sass converter...
Syntax error: File to import not found or unreadable: hashgrid.
  Load path: /home/malte/work/private/prspktve.github.com
  on line 8 of /home/malte/work/private/prspktve.github.com/css/layout.scss
```

Seems like you forgot to add _hashgrid.scss to version control. Commenting out the specified line in layout.scss helps, but I'm missing the wonderful hashgrid :-)

**Comment by prspktve** [comment]
Ja ich tu es am besten mit ins repo :)
